name: build nodepro
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - nodepro/**
jobs:
  push:
    name: "sivium:nodepro_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 12
          - 14
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
    steps:
      - uses: actions/checkout@v4
      # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./nodepro
          file: ./nodepro/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/siviumsolutions/docker-eggs:nodejs_${{ matrix.tag }}
            ghcr.io/siviumsolutions/nodepro_${{ matrix.tag }}
